# Generated by Django 5.1.15 on 2026-09-21 22:25

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('raw_lots', '0001_initial'),
        ('tenants', '0001_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.CharField(choices=[('NEW_COLLECTION', 'New Collection (كريمة / سوبر لوكس)'), ('MIDDLE', 'Middle (وسط / درجة ثانية)'), ('CLEARANCE', 'Clearance (تصفيات / شعبي)'), ('WASTE', 'Waste (تالف / هالك فرز)')], db_index=True, default='NEW_COLLECTION', max_length=30)),
                ('total_weight_kg', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Available Weight (KG)')),
                ('total_quantity_pieces', models.IntegerField(default=0, verbose_name='Available Pieces')),
                ('avg_cost_per_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Current Unit Cost per KG')),
                ('current_total_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Current Valuation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='products.product')),
                ('source_lot', models.ForeignKey(blank=True, help_text='Direct link to source raw bale for full traceability', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_stock_items', to='raw_lots.rawlot')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'stock_items',
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('SORT_IN', 'Sorting Good Output (إدخال من الفرز)'), ('SALE', 'POS / Customer Sale (صرف بيع)'), ('RETURN_IN', 'Sales Return (إرجاع مبيعات)'), ('TRANSFER_OUT', 'Transfer Out (نقل صادر لمخزن آخر)'), ('TRANSFER_IN', 'Transfer In (نقل وارد من مخزن آخر)'), ('ADJUSTMENT_PLUS', 'Stock Count Surplus (تسوية جرد بالزيادة)'), ('ADJUSTMENT_MINUS', 'Stock Count Deficit (تسوية جرد بالعجز)'), ('WRITE_DOWN', 'Inventory Write-Down (تخفيض قيمة المخزون)')], db_index=True, max_length=30)),
                ('grade', models.CharField(choices=[('NEW_COLLECTION', 'New Collection (كريمة / سوبر لوكس)'), ('MIDDLE', 'Middle (وسط / درجة ثانية)'), ('CLEARANCE', 'Clearance (تصفيات / شعبي)'), ('WASTE', 'Waste (تالف / هالك فرز)')], max_length=30)),
                ('weight_change_kg', models.DecimalField(decimal_places=3, help_text='Signed weight change (+ for in, - for out)', max_digits=12)),
                ('quantity_change_pieces', models.IntegerField(default=0, help_text='Signed pieces change (+ for in, - for out)')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Unit cost applied at transaction time', max_digits=12)),
                ('total_cost_change', models.DecimalField(decimal_places=2, help_text='Total value change (+ for increase, - for decrease)', max_digits=14)),
                ('source_document_type', models.CharField(help_text='e.g. SortingOrder, SaleInvoice, TransferOrder', max_length=100)),
                ('source_document_id', models.CharField(db_index=True, help_text='UUID or Code of source document', max_length=100)),
                ('running_weight_balance', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_ledger', to='products.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_ledger', to='warehouses.warehouse')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.stockitem')),
            ],
            options={
                'db_table': 'inventory_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.UniqueConstraint(fields=('tenant', 'product', 'grade', 'warehouse', 'source_lot'), name='unique_stock_item_per_lot_grade_wh'),
        ),
    ]
