# Generated by Django 5.1.15 on 2026-09-21 22:26

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Discount Name')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo Code')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage Discount (نسبة مئوية %)'), ('FIXED_AMOUNT', 'Fixed Amount Discount (مبلغ ثابت ج.م)')], default='PERCENTAGE', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Discount percentage value (e.g. 10.00 for 10%) or fixed EGP amount', max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum allowed discount cap in EGP', max_digits=12, null=True)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum invoice subtotal required to apply discount', max_digits=12)),
                ('required_role', models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('CASHIER', 'Cashier'), ('WAREHOUSE_KEEPER', 'Warehouse Keeper'), ('ACCOUNTANT', 'Accountant'), ('SORTER', 'Sorter')], default='CASHIER', help_text='Minimum authority role required to apply this discount', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'discount_rules',
                'ordering': ['name'],
            },
        ),
    ]
