# Generated by Django 5.1.15 on 2026-09-21 22:26

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('products', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Price List Name')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Price List Code')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Global Default')),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Optional: branch specific price list (null = global default)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_lists', to='branches.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'price_lists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.CharField(choices=[('NEW_COLLECTION', 'New Collection (كريمة / سوبر لوكس)'), ('MIDDLE', 'Middle (وسط / درجة ثانية)'), ('CLEARANCE', 'Clearance (تصفيات / شعبي)'), ('WASTE', 'Waste (تالف / هالك فرز)')], db_index=True, default='NEW_COLLECTION', max_length=30)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Selling Price per KG')),
                ('price_per_piece', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Selling Price per Piece (Optional)')),
                ('is_active', models.BooleanField(default=True)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pricing.pricelist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_list_items', to='products.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'price_list_items',
                'constraints': [models.UniqueConstraint(fields=('price_list', 'product', 'grade'), name='unique_product_grade_per_pricelist')],
            },
        ),
    ]
