# Generated by Django 5.1.15 on 2026-09-21 22:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Template Name')),
                ('template_type', models.CharField(choices=[('POS_RECEIPT', 'POS Sales Receipt (فاتورة بيع حرارية)'), ('SHIFT_SUMMARY', 'Shift Handover Slip (إيصال إغلاق الوردية)'), ('BALE_TAG', 'Bale Sorting Tag (استيكر / كارت الفرز)')], default='POS_RECEIPT', max_length=30)),
                ('width', models.CharField(choices=[('80MM', '80mm Standard Thermal (طابعة 80 مم)'), ('58MM', '58mm Compact Thermal (طابعة 58 مم)')], default='80MM', max_length=10)),
                ('header_text', models.TextField(blank=True, help_text='Store name, slogan, branch info', null=True)),
                ('footer_text', models.TextField(blank=True, help_text='Return policy, thank you message', null=True)),
                ('show_logo', models.BooleanField(default=False)),
                ('show_barcode', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'print_templates',
                'ordering': ['name'],
            },
        ),
    ]
