# Generated by Django 5.1.15 on 2026-09-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printtemplate',
            name='show_address',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='printtemplate',
            name='show_phone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='printtemplate',
            name='show_tax',
            field=models.BooleanField(default=False),
        ),
    ]
