# Generated by Django 5.1.15 on 2026-09-21 22:37

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0001_initial'),
        ('tenants', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCountSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_code', models.CharField(db_index=True, max_length=100, verbose_name='Count Session #')),
                ('count_date', models.DateField(verbose_name='Count Date')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress (قيد الجرد الفعلي)'), ('COMPLETED', 'Completed & Audited (مكتمل بانتظار الاعتماد)'), ('APPLIED', 'Applied to Ledger (تم تطبيق التسوية بالدفاتر)'), ('CANCELLED', 'Cancelled (ملغي)')], db_index=True, default='IN_PROGRESS', max_length=20)),
                ('total_weight_difference', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('total_cost_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes', models.TextField(blank=True, null=True)),
                ('counted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_counts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'stock_count_sessions',
                'ordering': ['-count_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockCountLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.CharField(choices=[('NEW_COLLECTION', 'New Collection (كريمة / سوبر لوكس)'), ('MIDDLE', 'Middle (وسط / درجة ثانية)'), ('CLEARANCE', 'Clearance (تصفيات / شعبي)'), ('WASTE', 'Waste (تالف / هالك فرز)')], max_length=30)),
                ('system_weight_kg', models.DecimalField(decimal_places=3, max_digits=12)),
                ('counted_weight_kg', models.DecimalField(decimal_places=3, max_digits=12)),
                ('weight_difference_kg', models.DecimalField(decimal_places=3, help_text='Counted - System', max_digits=12)),
                ('system_quantity_pieces', models.IntegerField(default=0)),
                ('counted_quantity_pieces', models.IntegerField(default=0)),
                ('quantity_difference_pieces', models.IntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_adjustment_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='count_lines', to='inventory.stockitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stock_count.stockcountsession')),
            ],
            options={
                'db_table': 'stock_count_line_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='stockcountsession',
            constraint=models.UniqueConstraint(fields=('tenant', 'session_code'), name='unique_stock_count_session_code_per_tenant'),
        ),
    ]
