# Generated by Django 5.1.15 on 2026-09-25 07:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Delivery Fee (مصاريف التوصيل)'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Previous Customer Balance (الرصيد السابق للعميل)'),
        ),
    ]
