# Generated by Django 5.1.15 on 2026-09-26 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_offer_pieces_coupons'),
        ('sales', '0002_add_delivery_fee_and_previous_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='applied_offers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='salelineitem',
            name='bundle_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salelineitem',
            name='display_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='salelineitem',
            name='offer_label',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='salelineitem',
            name='piece_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_lines', to='pricing.pieceitem'),
        ),
    ]
