# Generated by Django 5.1.15 on 2026-09-26 12:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_code'),
        ('payments', '0001_initial'),
        ('pos', '0001_initial'),
        ('sales', '0003_pos_v2'),
        ('shifts', '0001_initial'),
        ('tenants', '0003_add_logo_base64_to_tenant'),
        ('warehouses', '0002_add_store_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeferredSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(db_index=True, max_length=40)),
                ('lines', models.JSONField(blank=True, default=list)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('due_date', models.DateField()),
                ('status', models.CharField(db_index=True, default='OPEN', max_length=12)),
                ('transfer_out_code', models.CharField(blank=True, max_length=40, null=True)),
                ('transfer_back_code', models.CharField(blank=True, max_length=40, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deferred_sales_made', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deferred_sales', to='customers.customer')),
                ('deposit_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payments.paymentmethod')),
                ('holding_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='warehouses.warehouse')),
                ('sale_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_deferred', to='sales.saleinvoice')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deferred_sales', to='shifts.shift')),
                ('shop_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='warehouses.warehouse')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deferred_sales', to='pos.posterminal')),
            ],
            options={
                'db_table': 'deferred_sales',
                'ordering': ['-created_at'],
            },
        ),
    ]
