# Generated by Django 5.1.15 on 2026-09-26 21:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_deferred_sales'),
        ('tenants', '0003_add_logo_base64_to_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=30)),
                ('prefix', models.CharField(blank=True, default='', max_length=20)),
                ('next_value', models.PositiveBigIntegerField(default=1)),
                ('padding', models.PositiveSmallIntegerField(default=6)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'number_sequences',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'key'), name='unique_number_sequence')],
            },
        ),
    ]
