# Generated by Django 5.1.15 on 2026-09-25 23:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
        ('tenants', '0003_add_logo_base64_to_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaselineitem',
            name='bale_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaselineitem',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaselineitem',
            name='extra_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaselineitem',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaselineitem',
            name='item_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='purchaselineitem',
            name='purchase_kind',
            field=models.CharField(blank=True, choices=[('BALE', 'Bale (بالة)'), ('STOCK', 'Stock (استوك)'), ('DIRECT', 'Direct Purchase (شراء مباشر)')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaselineitem',
            name='segment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaselineitem',
            name='stock_type',
            field=models.CharField(blank=True, choices=[('ONE_BRAND', 'One Brand'), ('MIX_BRAND', 'Mix Brand')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='PurchaseOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option_type', models.CharField(choices=[('BALE_TYPE', 'Bale Type (نوع البالة)'), ('SEGMENT', 'Segment (الصنف)'), ('BRAND', 'Brand (البراند)'), ('SPECIAL_ITEM', 'Special Item (بند خاص)')], db_index=True, max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'purchase_options',
                'ordering': ['option_type', 'name'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'option_type', 'name'), name='unique_purchase_option_per_tenant')],
            },
        ),
    ]
