# Generated by Django 5.1.15 on 2026-09-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_purchase_screen_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseoption',
            name='option_type',
            field=models.CharField(choices=[('BALE_TYPE', 'Bale Type (نوع البالة)'), ('SEGMENT', 'Segment (الصنف)'), ('BRAND', 'Brand (البراند)'), ('SPECIAL_ITEM', 'Special Item (بند خاص)'), ('SEASON', 'Season (الموسم)')], db_index=True, max_length=20),
        ),
    ]
