# Generated by Django 5.1.15 on 2026-09-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_supplier_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaselineitem',
            name='brands',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='purchaselineitem',
            name='direct_category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaselineitem',
            name='season',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaselineitem',
            name='ton_group',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='purchaselineitem',
            name='ton_type',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchaseoption',
            name='option_type',
            field=models.CharField(choices=[('BALE_TYPE', 'Bale Type (نوع البالة)'), ('SEGMENT', 'Segment (الصنف)'), ('BRAND', 'Brand (البراند)'), ('SPECIAL_ITEM', 'Special Item (بند خاص)'), ('SEASON', 'Season (الموسم)'), ('ITEM', 'Bale item'), ('CATEGORY', 'Direct purchase category')], db_index=True, max_length=20),
        ),
    ]
