# Generated by Django 5.1.15 on 2026-09-21 22:30

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treasury',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Treasury Name')),
                ('treasury_type', models.CharField(choices=[('MAIN_SAFE', 'Main Safe (الخزينة الرئيسية)'), ('POS_DRAWER', 'POS Cash Drawer (درج الكاشير)'), ('BANK', 'Bank Account (حساب بنكي)')], default='MAIN_SAFE', max_length=20)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='Current Balance (Sum of Ledger)')),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasuries', to='branches.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'treasuries',
                'db_table': 'treasuries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TreasuryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit / Income (إيداع / وارد)'), ('WITHDRAWAL', 'Withdrawal / Expense (سحب / منصرف)'), ('TRANSFER_IN', 'Transfer In (تحويل وارد)'), ('TRANSFER_OUT', 'Transfer Out (تحويل صادر)')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Signed amount (+ increases balance, - decreases balance)', max_digits=16)),
                ('payment_method_name', models.CharField(blank=True, help_text='Payment method name (e.g. Cash, Visa)', max_length=100, null=True)),
                ('source_document_type', models.CharField(blank=True, max_length=100, null=True)),
                ('source_document_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('running_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('description', models.TextField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('treasury', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='treasury.treasury')),
            ],
            options={
                'db_table': 'treasury_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
