# Generated by Django 5.1.15 on 2026-09-26 07:39

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
        ('tenants', '0003_add_logo_base64_to_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('offer_type', models.CharField(max_length=20)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('targets', models.JSONField(blank=True, default=dict)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('time_from', models.TimeField(blank=True, null=True)),
                ('time_to', models.TimeField(blank=True, null=True)),
                ('days', models.JSONField(blank=True, default=list)),
                ('shops', models.JSONField(blank=True, default=list)),
                ('apply_mode', models.CharField(default='CASHIER', max_length=10)),
                ('stackable', models.BooleanField(default=False)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('required_role', models.CharField(default='ANY', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'offers_v2',
                'ordering': ['-created_at'],
            },
        ),
    ]
