# Generated by Django 5.1.15 on 2026-09-25 07:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carton_capacity',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=10, verbose_name='Carton Capacity (سعة الكرتونة)'),
        ),
        migrations.AddField(
            model_name='product',
            name='carton_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Carton Price (سعر الكرتونة / الشيكارة)'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_stock_level',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, verbose_name='Min Stock Alert (الحد الأدنى)'),
        ),
        migrations.AddField(
            model_name='product',
            name='opening_balance',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Opening Stock (رصيد أول المدة)'),
        ),
        migrations.AddField(
            model_name='product',
            name='package_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Package Type (نوع العبوة)'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Purchase Price (سعر الشراء)'),
        ),
        migrations.AddField(
            model_name='product',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Retail Price (سعر البيع القطاعي)'),
        ),
        migrations.AddField(
            model_name='product',
            name='special_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Special Price (سعر بيع خاص)'),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Wholesale Code (كود الجملة)'),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Wholesale Price (سعر بيع الجملة)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Barcode / EAN (الباركود)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Internal SKU / Code (الكود)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Product Name (اسم الصنف)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(choices=[('PIECE', 'قطعة / عدد'), ('KG', 'كيلو / كجم'), ('BOTH', 'قطعة + وزن'), ('BALE', 'باله'), ('DOZEN', 'دسته'), ('CARTON', 'كرتونه'), ('SACK', 'شيكارة'), ('BARREL', 'برميل'), ('BOX', 'علبة'), ('JAR', 'برطمان'), ('JERRYCAN', 'جركن'), ('LITER', 'لتر'), ('BAG', 'كيس'), ('TANK', 'تنك'), ('BUNDLE', 'هبط'), ('SET', 'مجموعة'), ('EMPTY', 'فوارغ'), ('CARD', 'كارت'), ('TOTE', 'شنطة'), ('LIST', 'لسته'), ('OTHER', 'غير محدد')], default='PIECE', max_length=30, verbose_name='Default Unit of Measure (وحدة القياس)'),
        ),
    ]
