# Generated by Django 5.1.15 on 2026-09-21 22:35

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0001_initial'),
        ('sales', '0001_initial'),
        ('shifts', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_number', models.CharField(db_index=True, max_length=100, verbose_name='Return #')),
                ('return_date_time', models.DateTimeField(verbose_name='Return Date/Time')),
                ('total_refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_cogs_reversed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed (مكتمل ومسترجع)'), ('CANCELLED', 'Cancelled (ملغي)')], db_index=True, default='COMPLETED', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_returns', to=settings.AUTH_USER_MODEL)),
                ('original_sale_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.saleinvoice')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='shifts.shift')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'sales_returns',
                'ordering': ['-return_date_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturnLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.CharField(choices=[('NEW_COLLECTION', 'New Collection (كريمة / سوبر لوكس)'), ('MIDDLE', 'Middle (وسط / درجة ثانية)'), ('CLEARANCE', 'Clearance (تصفيات / شعبي)'), ('WASTE', 'Waste (تالف / هالك فرز)')], max_length=30)),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Returned Weight (KG)')),
                ('quantity_pieces', models.IntegerField(default=0, verbose_name='Returned Pieces')),
                ('refund_unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('refund_total_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cogs_reversed', models.DecimalField(decimal_places=2, max_digits=14)),
                ('original_sale_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='sales.salelineitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='returns.salesreturn')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='inventory.stockitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'sales_return_line_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='salesreturn',
            constraint=models.UniqueConstraint(fields=('tenant', 'return_number'), name='unique_sales_return_number_per_tenant'),
        ),
    ]
