# Generated by Django 5.1.15 on 2026-09-26 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_code'),
        ('payments', '0001_initial'),
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturn',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_returns', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='refund_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payments.paymentmethod'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='refund_to_credit',
            field=models.BooleanField(default=False),
        ),
    ]
