# Generated by Django 5.1.15 on 2026-10-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_receipt_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='promo_prices',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
