# Generated by Django 5.1.15 on 2026-09-21 22:21

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('raw_lots', '0001_initial'),
        ('tenants', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SortingOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_code', models.CharField(db_index=True, max_length=100, verbose_name='Sorting Order Code')),
                ('sorting_date', models.DateField(verbose_name='Sorting Date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft / Sorting In Progress (مسودة / قيد الفرز)'), ('COMPLETED', 'Completed & Reconciled (مكتمل ومعتمد)'), ('CANCELLED', 'Cancelled (ملغي)')], db_index=True, default='DRAFT', max_length=20)),
                ('reconciliation_status', models.CharField(choices=[('BALANCED', 'Balanced (متطابق بالوزن)'), ('UNBALANCED', 'Unbalanced (غير متطابق)')], db_index=True, default='UNBALANCED', max_length=20)),
                ('total_good_weight_kg', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Total Good Output Weight (KG)')),
                ('total_waste_weight_kg', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Total Waste Weight (KG)')),
                ('adjustment_weight_kg', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Approved adjustment difference (if any)', max_digits=12)),
                ('adjustment_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('raw_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sorting_orders', to='raw_lots.rawlot', verbose_name='Source Raw Bale / Lot')),
                ('sorter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_sortings', to=settings.AUTH_USER_MODEL, verbose_name='Sorter / Responsible User')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'sorting_orders',
                'ordering': ['-sorting_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SortingOutputLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.CharField(choices=[('NEW_COLLECTION', 'New Collection (كريمة / سوبر لوكس)'), ('MIDDLE', 'Middle (وسط / درجة ثانية)'), ('CLEARANCE', 'Clearance (تصفيات / شعبي)'), ('WASTE', 'Waste (تالف / هالك فرز)')], max_length=30, verbose_name='Output Grade')),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Weight (KG)')),
                ('quantity_pieces', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantity (Pieces)')),
                ('allocated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Allocated Cost Total')),
                ('cost_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Calculated Cost per KG')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sorting_outputs', to='products.product', verbose_name='Target Catalog Product')),
                ('sorting_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_lines', to='sorting.sortingorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sorting_outputs', to='warehouses.warehouse', verbose_name='Destination Warehouse')),
            ],
            options={
                'db_table': 'sorting_output_lines',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SortingWasteLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Waste Weight (KG)')),
                ('quantity_pieces', models.PositiveIntegerField(blank=True, null=True, verbose_name='Waste Quantity (Pieces)')),
                ('classification', models.CharField(choices=[('NORMAL', 'Normal / Expected Waste (هالك طبيعي متوقع)'), ('ABNORMAL', 'Abnormal / Exceptional Waste (هالك غير طبيعي / استثنائي)')], default='NORMAL', max_length=20, verbose_name='Waste Classification')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Waste Reason / Defect Notes')),
                ('allocated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Allocated Waste Cost')),
                ('sorting_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_lines', to='sorting.sortingorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'sorting_waste_lines',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='sortingorder',
            constraint=models.UniqueConstraint(fields=('tenant', 'order_code'), name='unique_sorting_order_code_per_tenant'),
        ),
    ]
