# Generated by Django 5.1.15 on 2026-09-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortingoutputline',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Sorting Brand'),
        ),
        migrations.AddField(
            model_name='sortingoutputline',
            name='item_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Sorting Item'),
        ),
    ]
