# Generated by Django 5.1.15 on 2026-09-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorting', '0002_sorting_lines_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortingoutputline',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sortingoutputline',
            name='item_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
