# Generated by Django 5.1.15 on 2026-09-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
