# Generated by Django 5.1.15 on 2026-09-21 22:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('tenants', '0001_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=100, verbose_name='Supplier Invoice #')),
                ('invoice_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft (مسودة)'), ('CONFIRMED', 'Confirmed (مؤكدة)'), ('RECEIVED', 'Received / Goods In (مستلمة بالمخزن)'), ('CANCELLED', 'Cancelled (ملغاة)')], db_index=True, default='DRAFT', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('additional_costs', models.DecimalField(decimal_places=2, default=0.0, help_text='Freight, customs, transport costs to be absorbed', max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('notes', models.TextField(blank=True, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='suppliers.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('warehouse', models.ForeignKey(help_text='Receiving Warehouse / Sorting Area', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'purchase_invoices',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('RAW_BALE', 'Raw Bale / Lot (بالة خام للفرز)'), ('FINISHED_GOODS', 'Direct Finished Goods (بضاعة جاهزة)')], default='RAW_BALE', max_length=20)),
                ('description', models.CharField(max_length=255, verbose_name='Item / Bale Description')),
                ('weight_kg', models.DecimalField(decimal_places=3, default=0.0, help_text='Total Weight in KG (دقة 3 خانات عشرية)', max_digits=12)),
                ('quantity_pieces', models.PositiveIntegerField(blank=True, help_text='Estimated or counted piece count if applicable', null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('category', models.ForeignKey(blank=True, help_text='Target category of the bale (e.g. Mixed Summer, Jackets, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='products.category')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchasing.purchaseinvoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'purchase_line_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoice',
            constraint=models.UniqueConstraint(fields=('tenant', 'supplier', 'invoice_number'), name='unique_invoice_per_supplier_and_tenant'),
        ),
    ]
