# Generated by Django 5.1.15 on 2026-09-21 22:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('purchasing', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('tenants', '0001_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_code', models.CharField(db_index=True, max_length=100, verbose_name='Bale / Raw Lot ID')),
                ('original_weight_kg', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Original Received Weight (KG)')),
                ('original_quantity_pieces', models.PositiveIntegerField(blank=True, null=True, verbose_name='Original Estimated / Counted Pieces')),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Total Actual Purchase Cost')),
                ('status', models.CharField(choices=[('RECEIVED', 'Received / In Storage (مستلمة بالمخزن الخام)'), ('SORTING_IN_PROGRESS', 'Sorting In Progress (قيد الفرز)'), ('SORTED', 'Fully Sorted (تم الفرز والتوزيع بالكامل)'), ('CANCELLED', 'Cancelled (ملغاة)')], db_index=True, default='RECEIVED', max_length=30, verbose_name='Status')),
                ('received_date', models.DateField(verbose_name='Receiving Date')),
                ('notes', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_lots', to='products.category', verbose_name='Bale Category / Type')),
                ('purchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_lots', to='purchasing.purchaseinvoice', verbose_name='Source Purchase Invoice')),
                ('purchase_line_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_lots', to='purchasing.purchaselineitem', verbose_name='Source Invoice Line')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_lots', to='suppliers.supplier', verbose_name='Supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_lots', to='warehouses.warehouse', verbose_name='Current Storage Warehouse')),
            ],
            options={
                'db_table': 'raw_lots',
                'ordering': ['-received_date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'lot_code'), name='unique_raw_lot_code_per_tenant')],
            },
        ),
    ]
