# Generated by Django 5.1.15 on 2026-09-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_lots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawlot',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='rawlot',
            name='category_name',
            field=models.CharField(blank=True, default='بلوزه', max_length=100),
        ),
        migrations.AddField(
            model_name='rawlot',
            name='purchase_grade',
            field=models.CharField(blank=True, default='سوبر كريم', max_length=50),
        ),
        migrations.AddField(
            model_name='rawlot',
            name='season',
            field=models.CharField(blank=True, default='صيفي', max_length=50),
        ),
        migrations.AddField(
            model_name='rawlot',
            name='segment',
            field=models.CharField(blank=True, default='حريمي', max_length=50),
        ),
        migrations.AddField(
            model_name='rawlot',
            name='source_kind',
            field=models.CharField(blank=True, default='بالة', max_length=50),
        ),
    ]
