# Generated by Django 5.1.15 on 2026-09-21 22:33

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift_code', models.CharField(db_index=True, max_length=100, verbose_name='Shift #')),
                ('opened_at', models.DateTimeField(verbose_name='Opened At')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed At')),
                ('status', models.CharField(choices=[('OPEN', 'Open / Active (مفتوحة)'), ('CLOSED', 'Closed (مغلقة ومطابقة)'), ('REVIEW', 'Closed with Discrepancy / Under Review (مغلقة بفرق عجز/زيادة)')], db_index=True, default='OPEN', max_length=20)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Opening Float (رصيد الافتتاح)')),
                ('cash_sales_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Cash Collected from Sales')),
                ('expected_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Expected Cash in Drawer')),
                ('actual_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Actual Cash Counted by Cashier')),
                ('difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual - Expected (Negative = Shortage, Positive = Surplus)', max_digits=14)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to=settings.AUTH_USER_MODEL, verbose_name='Cashier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='pos.posterminal')),
            ],
            options={
                'db_table': 'shifts',
                'ordering': ['-opened_at'],
            },
        ),
    ]
