# Generated by Django 5.1.15 on 2026-09-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo_base64',
            field=models.TextField(blank=True, null=True, verbose_name='Company Logo Base64'),
        ),
    ]
