# Generated by Django 5.1.15 on 2026-09-21 22:25

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raw_lots', '0001_initial'),
        ('sorting', '0001_initial'),
        ('tenants', '0001_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Waste Weight (KG)')),
                ('quantity_pieces', models.PositiveIntegerField(blank=True, null=True, verbose_name='Waste Pieces (if counted)')),
                ('classification', models.CharField(choices=[('NORMAL', 'Normal / Expected Waste (هالك طبيعي متوقع)'), ('ABNORMAL', 'Abnormal / Exceptional Waste (هالك غير طبيعي / استثنائي)')], default='NORMAL', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('allocated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Financial cost recognized for this waste', max_digits=14)),
                ('disposal_status', models.CharField(choices=[('PENDING', 'Pending in Waste Storage (في مخزن الهالك / معلق)'), ('DISPOSED', 'Disposed / Destroyed (تم الإعدام / التخلص)'), ('SOLD_AS_SCRAP', 'Sold as Scrap / Rags (تم البيع كخردة / أقمشة)')], db_index=True, default='PENDING', max_length=30)),
                ('disposal_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Revenue if sold as scrap/rags', max_digits=14)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('raw_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_records', to='raw_lots.rawlot')),
                ('sorting_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_records', to='sorting.sortingorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_records', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'waste_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
