# Generated by Django 5.1.15 on 2026-09-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('MAIN', 'Main Store / Sales Floor'), ('SORTING', 'Sorting Area'), ('TRANSIT', 'In-Transit Storage'), ('RETURNS', 'Returns Warehouse'), ('STORE', 'Retail Store / Shop (محل)')], default='MAIN', max_length=30),
        ),
    ]
