# Generated by Django 5.1.15 on 2026-09-21 22:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('tenants', '0001_initial'),
        ('treasury', '0001_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSTerminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Terminal Name')),
                ('code', models.CharField(db_index=True, max_length=50, verbose_name='Terminal Code')),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_terminals', to='branches.branch')),
                ('cash_drawer', models.ForeignKey(help_text='Treasury drawer holding this POS cash', on_delete=django.db.models.deletion.PROTECT, related_name='pos_terminals', to='treasury.treasury')),
                ('default_warehouse', models.ForeignKey(help_text='Warehouse from which this POS decrements inventory', on_delete=django.db.models.deletion.PROTECT, related_name='pos_terminals', to='warehouses.warehouse')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'pos_terminals',
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'code'), name='unique_terminal_code_per_tenant')],
            },
        ),
    ]
