# Generated by Django 5.1.15 on 2026-09-21 22:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('treasury', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Payment Method Name')),
                ('method_type', models.CharField(choices=[('CASH', 'Cash (نقدي)'), ('ELECTRONIC', 'Electronic / Card / Wallet (فيزا / محفظة إلكترونية)'), ('CREDIT', 'Credit / Deferred (آجل على العميل)')], default='CASH', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('treasury', models.ForeignKey(blank=True, help_text='Target treasury that receives funds from this method', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_methods', to='treasury.treasury')),
            ],
            options={
                'db_table': 'payment_methods',
                'ordering': ['name'],
            },
        ),
    ]
