# Generated by Django 5.1.15 on 2026-09-21 22:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sorting', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostingCalculationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method_used', models.CharField(max_length=50)),
                ('waste_treatment_used', models.CharField(max_length=50)),
                ('parameters_used', models.JSONField(default=dict)),
                ('variance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('waste_loss_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('total_allocated_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('sorting_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costing_records', to='sorting.sortingorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'costing_calculation_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CostingConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Default Costing Policy', max_length=255)),
                ('method', models.CharField(choices=[('EQUAL_WEIGHT', 'Equal Weight Allocation (التوزيع بالوزن بالتساوي)'), ('COEFFICIENTS', 'Weighted Coefficients (التوزيع بالمعاملات)'), ('SALES_VALUE', 'Relative Sales Value (التوزيع بالقيمة البيعية المتوقعة)'), ('STANDARD', 'Standard Costing (التكلفة المعيارية مع الفروقات)')], default='EQUAL_WEIGHT', max_length=30)),
                ('waste_treatment', models.CharField(choices=[('ABSORBED', 'Absorbed by Good Output (امتصاص الهالك)'), ('SEPARATE', 'Recognized as Separate Loss (خسارة منفصلة)'), ('SPLIT', 'Split Normal/Abnormal (طبيعي ممتص / زائد كخسارة)')], default='ABSORBED', max_length=30)),
                ('normal_waste_percentage', models.DecimalField(decimal_places=2, default=5.0, help_text='Expected normal waste percentage (e.g. 5.00 for 5%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'costing_configurations',
            },
        ),
        migrations.CreateModel(
            name='CostingParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.CharField(choices=[('NEW_COLLECTION', 'New Collection (كريمة / سوبر لوكس)'), ('MIDDLE', 'Middle (وسط / درجة ثانية)'), ('CLEARANCE', 'Clearance (تصفيات / شعبي)'), ('WASTE', 'Waste (تالف / هالك فرز)')], max_length=30, verbose_name='Product Grade')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, help_text='Coefficient multiplier (Method B)', max_digits=8)),
                ('expected_selling_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Expected selling price per KG (Method C)', max_digits=12)),
                ('standard_cost_per_kg', models.DecimalField(decimal_places=2, default=0.0, help_text='Standard cost per KG (Method D)', max_digits=12)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='costing.costingconfiguration')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'costing_parameters',
            },
        ),
        migrations.AddConstraint(
            model_name='costingconfiguration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'is_active'), name='unique_active_costing_config_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='costingparameter',
            constraint=models.UniqueConstraint(fields=('configuration', 'grade'), name='unique_grade_parameter_per_configuration'),
        ),
    ]
