# Generated by Django 5.1.15 on 2026-09-28 19:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0001_initial'),
        ('sorting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costingcalculationrecord',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='costingconfiguration',
            name='unique_active_costing_config_per_tenant',
        ),
        migrations.RemoveConstraint(
            model_name='costingparameter',
            name='unique_grade_parameter_per_configuration',
        ),
        migrations.AddField(
            model_name='costingconfiguration',
            name='high_grade_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('55.00'), max_digits=5, verbose_name='نسبة العالي %'),
        ),
        migrations.AddField(
            model_name='costingconfiguration',
            name='liquidation_grade_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='نسبة التصفيات %'),
        ),
        migrations.AddField(
            model_name='costingconfiguration',
            name='mid_grade_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5, verbose_name='نسبة الوسط %'),
        ),
        migrations.AddField(
            model_name='costingconfiguration',
            name='waste_grade_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='نسبة الهالك %'),
        ),
        migrations.AlterField(
            model_name='costingcalculationrecord',
            name='method_used',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='costingcalculationrecord',
            name='sorting_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='costing_record', to='sorting.sortingorder'),
        ),
        migrations.AlterField(
            model_name='costingcalculationrecord',
            name='total_allocated_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='costingcalculationrecord',
            name='variance_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='costingcalculationrecord',
            name='waste_loss_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='costingcalculationrecord',
            name='waste_treatment_used',
            field=models.CharField(default='SEPARATE', max_length=30),
        ),
        migrations.AlterField(
            model_name='costingconfiguration',
            name='method',
            field=models.CharField(choices=[('PIECE', 'بالقطعة (تكلفة موحدة لكل قطعة)'), ('WEIGHT', 'بالوزن (تكلفة موحدة لكل كيلو)'), ('PERCENTAGE', 'بنسب ثابتة لكل درجة (عالي / وسط / تصفيات / هالك)'), ('EQUAL_WEIGHT', 'Equal Weight Allocation (قديم)'), ('COEFFICIENTS', 'Weighted Coefficients (قديم)'), ('SALES_VALUE', 'Relative Sales Value (قديم)'), ('STANDARD', 'Standard Costing (قديم)')], default='WEIGHT', max_length=30, verbose_name='طريقة حساب التكلفة'),
        ),
        migrations.AlterField(
            model_name='costingconfiguration',
            name='name',
            field=models.CharField(default='سياسة التكلفة الافتراضية', max_length=255),
        ),
        migrations.AlterField(
            model_name='costingconfiguration',
            name='normal_waste_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='نسبة الهالك المعيارية', max_digits=5),
        ),
        migrations.AlterField(
            model_name='costingconfiguration',
            name='waste_treatment',
            field=models.CharField(choices=[('SEPARATE', 'تسجيل الهالك كخسارة منفصلة (خسارة هالك الفرز)'), ('ABSORBED', 'Absorbed by Good Output (قديم)'), ('SPLIT', 'Split Normal/Abnormal (قديم)')], default='SEPARATE', max_length=30, verbose_name='معالجة الهالك'),
        ),
        migrations.AlterField(
            model_name='costingparameter',
            name='coefficient',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='costingparameter',
            name='expected_selling_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='costingparameter',
            name='grade',
            field=models.CharField(choices=[('NEW_COLLECTION', 'New Collection (كريمة / سوبر لوكس)'), ('MIDDLE', 'Middle (وسط / درجة ثانية)'), ('CLEARANCE', 'Clearance (تصفيات / شعبي)'), ('WASTE', 'Waste (تالف / هالك فرز)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='costingparameter',
            name='standard_cost_per_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
