import ExcelJS from 'exceljs';
import html2pdf from 'html2pdf.js';
import axiosClient from '../api/axiosClient';

let companyCache = null;

export async function getCompanyInfo() {
  if (companyCache) return companyCache;
  try {
    const res = await axiosClient.get('/tenants/public_info/');
    companyCache = { name: res.data?.name || 'Motion Store', logo: res.data?.logo_base64 || null };
  } catch (e) {
    companyCache = { name: 'Motion Store', logo: null };
  }
  return companyCache;
}

const pad = (n) => String(n).padStart(2, '0');
export function nowStamp() {
  const d = new Date();
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`;
}
const fileStamp = () => {
  const d = new Date();
  return `${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}-${pad(d.getHours())}${pad(d.getMinutes())}`;
};
const isNumType = (t) => t === 'number' || t === 'money';
const fmtNum = (v, t) => {
  const n = Number(v || 0);
  return t === 'money'
    ? n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
    : n.toLocaleString('en-US', { maximumFractionDigits: 3 });
};
const esc = (s) => String(s ?? '').replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));

function labels(isRTL) {
  return isRTL
    ? { printed: 'تاريخ الطباعة', filter: 'البحث', total: 'الإجمالي', count: 'عدد السجلات', footer: 'تم إنشاء التقرير بواسطة Motion Store' }
    : { printed: 'Printed on', filter: 'Search', total: 'Total', count: 'Records', footer: 'Generated by Motion Store' };
}

function downloadBlob(blob, name) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = name;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 2000);
}

export async function exportToExcel({ title, columns, rows, totals = null, filtersText = '', filename, isRTL = true }) {
  const co = await getCompanyInfo();
  const L = labels(isRTL);
  const n = columns.length;
  const wb = new ExcelJS.Workbook();
  wb.creator = 'Motion Store';
  const sheetName = (title || 'Report').replace(/[\\/?*[\]:]/g, ' ').slice(0, 30);
  const ws = wb.addWorksheet(sheetName, {
    views: [{ rightToLeft: isRTL, showGridLines: false }],
    pageSetup: { paperSize: 9, orientation: n > 6 ? 'landscape' : 'portrait', fitToPage: true, fitToWidth: 1, fitToHeight: 0 }
  });
  ws.columns = columns.map((c) => ({ key: c.key, width: c.width || (isNumType(c.type) ? 16 : 22) }));

  const hasLogo = !!(co.logo && co.logo.startsWith('data:image'));
  if (hasLogo) {
    try {
      const ext = co.logo.includes('image/png') ? 'png' : (co.logo.includes('image/gif') ? 'gif' : 'jpeg');
      const id = wb.addImage({ base64: co.logo.split(',')[1], extension: ext });
      ws.addImage(id, { tl: { col: 0, row: 0 }, ext: { width: 72, height: 72 } });
    } catch (e) { /* logo optional */ }
  }
  const firstTextCol = hasLogo && n > 1 ? 2 : 1;
  const putHeader = (row, text, font) => {
    const r = ws.getRow(row);
    r.height = 20;
    if (n > firstTextCol) ws.mergeCells(row, firstTextCol, row, n);
    const cell = ws.getCell(row, firstTextCol);
    cell.value = text;
    cell.font = font;
    cell.alignment = { horizontal: isRTL ? 'right' : 'left', vertical: 'middle' };
  };
  putHeader(1, co.name, { bold: true, size: 16, color: { argb: 'FF047857' } });
  putHeader(2, title, { bold: true, size: 13, color: { argb: 'FF0F172A' } });
  putHeader(3, `${L.printed}: ${nowStamp()}   |   ${L.count}: ${rows.length}`, { size: 10, color: { argb: 'FF475569' } });
  putHeader(4, filtersText ? `${L.filter}: ${filtersText}` : '', { size: 10, color: { argb: 'FF475569' } });

  const border = { top: { style: 'thin', color: { argb: 'FFE2E8F0' } }, bottom: { style: 'thin', color: { argb: 'FFE2E8F0' } }, left: { style: 'thin', color: { argb: 'FFE2E8F0' } }, right: { style: 'thin', color: { argb: 'FFE2E8F0' } } };
  const headRowNo = 6;
  const head = ws.getRow(headRowNo);
  columns.forEach((c, i) => {
    const cell = head.getCell(i + 1);
    cell.value = c.header;
    cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF047857' } };
    cell.alignment = { horizontal: 'center', vertical: 'middle', wrapText: true };
    cell.border = border;
  });
  head.height = 24;

  rows.forEach((row, idx) => {
    const r = ws.getRow(headRowNo + 1 + idx);
    columns.forEach((c, i) => {
      const cell = r.getCell(i + 1);
      const v = row[c.key];
      cell.value = isNumType(c.type) ? Number(v || 0) : (v ?? '');
      if (c.type === 'money') cell.numFmt = '#,##0.00';
      if (c.type === 'number') cell.numFmt = '#,##0.###';
      cell.alignment = { horizontal: isNumType(c.type) ? 'center' : (isRTL ? 'right' : 'left'), vertical: 'middle', wrapText: true };
      cell.border = border;
      if (idx % 2 === 1) cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF8FAFC' } };
    });
  });

  let lastRow = headRowNo + rows.length;
  if (totals) {
    lastRow += 1;
    const r = ws.getRow(lastRow);
    columns.forEach((c, i) => {
      const cell = r.getCell(i + 1);
      if (i === 0) cell.value = L.total;
      else if (totals[c.key] !== undefined) {
        cell.value = Number(totals[c.key] || 0);
        if (c.type === 'money') cell.numFmt = '#,##0.00';
        if (c.type === 'number') cell.numFmt = '#,##0.###';
      }
      cell.font = { bold: true };
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFECFDF5' } };
      cell.alignment = { horizontal: isNumType(c.type) ? 'center' : (isRTL ? 'right' : 'left'), vertical: 'middle' };
      cell.border = border;
    });
  }
  const foot = ws.getCell(lastRow + 2, 1);
  if (n > 1) ws.mergeCells(lastRow + 2, 1, lastRow + 2, n);
  foot.value = L.footer;
  foot.font = { italic: true, size: 9, color: { argb: 'FF94A3B8' } };
  foot.alignment = { horizontal: 'center' };

  const buf = await wb.xlsx.writeBuffer();
  downloadBlob(new Blob([buf], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }), `${filename || 'report'}-${fileStamp()}.xlsx`);
}

export async function exportToPDF({ title, columns, rows, totals = null, filtersText = '', filename, isRTL = true }) {
  const co = await getCompanyInfo();
  const L = labels(isRTL);
  const landscape = columns.length > 6;
  const align = (c) => (isNumType(c.type) ? 'center' : (isRTL ? 'right' : 'left'));
  const cell = (c, v) => (isNumType(c.type) ? fmtNum(v, c.type) : esc(v ?? ''));
  const head = columns.map((c) => `<th style="background:#047857;color:#fff;padding:7px 6px;font-size:11px;text-align:${align(c)};border:1px solid #065f46">${esc(c.header)}</th>`).join('');
  const body = rows.map((row, i) => `<tr style="background:${i % 2 ? '#f8fafc' : '#ffffff'}">${columns.map((c) => `<td style="padding:6px;font-size:10.5px;border:1px solid #e2e8f0;text-align:${align(c)}">${cell(c, row[c.key])}</td>`).join('')}</tr>`).join('');
  const tot = totals
    ? `<tr style="background:#ecfdf5;font-weight:700">${columns.map((c, i) => `<td style="padding:7px 6px;font-size:11px;border:1px solid #a7f3d0;text-align:${align(c)}">${i === 0 ? esc(L.total) : (totals[c.key] !== undefined ? cell(c, totals[c.key]) : '')}</td>`).join('')}</tr>`
    : '';
  const logo = co.logo ? `<img src="${co.logo}" style="width:64px;height:64px;object-fit:contain" />` : '';
  const html = `
<div dir="${isRTL ? 'rtl' : 'ltr'}" style="font-family:'Cairo','Tahoma','Segoe UI',Arial,sans-serif;color:#0f172a;background:#ffffff;padding:4px;width:${landscape ? 1080 : 760}px">
  <div style="display:flex;align-items:center;justify-content:space-between;border-bottom:3px solid #047857;padding-bottom:10px;margin-bottom:12px">
    <div style="display:flex;align-items:center;gap:12px">${logo}
      <div>
        <div style="font-size:20px;font-weight:800;color:#047857">${esc(co.name)}</div>
        <div style="font-size:15px;font-weight:700;margin-top:2px">${esc(title)}</div>
      </div>
    </div>
    <div style="font-size:10.5px;color:#475569;line-height:1.7">
      <div>${L.printed}: ${nowStamp()}</div>
      <div>${L.count}: ${rows.length}</div>
      ${filtersText ? `<div>${L.filter}: ${esc(filtersText)}</div>` : ''}
    </div>
  </div>
  <table style="width:100%;border-collapse:collapse"><thead><tr>${head}</tr></thead><tbody>${body}${tot}</tbody></table>
  <div style="margin-top:14px;font-size:9.5px;color:#94a3b8;text-align:center">${L.footer}</div>
</div>`;

  await html2pdf()
    .set({
      margin: [8, 8, 12, 8],
      filename: `${filename || 'report'}-${fileStamp()}.pdf`,
      image: { type: 'jpeg', quality: 0.96 },
      html2canvas: { scale: 2, useCORS: true, backgroundColor: '#ffffff' },
      jsPDF: { unit: 'mm', format: 'a4', orientation: landscape ? 'landscape' : 'portrait' },
      pagebreak: { mode: ['css', 'legacy'], avoid: 'tr' }
    })
    .from(html, 'string')
    .toPdf()
    .get('pdf')
    .then((pdf) => {
      const total = pdf.internal.getNumberOfPages();
      const w = pdf.internal.pageSize.getWidth();
      const h = pdf.internal.pageSize.getHeight();
      for (let i = 1; i <= total; i++) {
        pdf.setPage(i);
        pdf.setFontSize(8);
        pdf.setTextColor(120);
        pdf.text(`${i} / ${total}`, w / 2, h - 5, { align: 'center' });
      }
    })
    .save();
}