# Generated by Django 5.1.15 on 2026-09-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('CASHIER', 'Cashier'), ('WAREHOUSE_KEEPER', 'Warehouse Keeper'), ('ACCOUNTANT', 'Accountant'), ('SORTER', 'Sorter')], db_index=True, max_length=50, unique=True)),
                ('allowed_screens', models.JSONField(default=list, help_text="List of frontend route paths allowed for this role. Example: ['/pos', '/reports']")),
            ],
            options={
                'verbose_name_plural': 'Role Permissions',
                'db_table': 'role_permissions',
            },
        ),
    ]
