# Generated by Django 5.1.15 on 2026-09-27 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_add_logo_base64_to_tenant'),
        ('users', '0002_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('CASHIER', 'Cashier'), ('WAREHOUSE_KEEPER', 'Warehouse Keeper'), ('ACCOUNTANT', 'Accountant'), ('SORTER', 'Sorter')], db_index=True, max_length=50),
        ),
    ]
