# Generated by Django 5.1.15 on 2026-09-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='allowed_actions',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
