# Generated by Django 5.1.15 on 2026-09-21 22:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Category Name')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Category Code')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Internal SKU / Code')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Barcode / EAN')),
                ('unit_of_measure', models.CharField(choices=[('PIECE', 'By Piece (بالقطعة)'), ('KG', 'By Weight / KG (بالوزن / كجم)'), ('BOTH', 'Piece + Weight Tracked (بالقطعة مع وزن فعلي)')], default='PIECE', max_length=20, verbose_name='Default Unit of Measure')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='Product Attributes (Size, Color, Gender, Season)')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_category_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False)), fields=('tenant', 'barcode'), name='unique_non_null_barcode_per_tenant'),
        ),
    ]
