# Generated by Django 5.1.15 on 2026-09-21 22:35

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        ('payments', '0001_initial'),
        ('pos', '0001_initial'),
        ('products', '0001_initial'),
        ('shifts', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=100, verbose_name='Sale Invoice #')),
                ('invoice_date_time', models.DateTimeField(verbose_name='Invoice Date/Time')),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed (مكتملة)'), ('REFUNDED', 'Fully Refunded (مسترجعة بالكامل)'), ('CANCELLED', 'Cancelled (ملغاة)')], db_index=True, default='COMPLETED', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Net Revenue')),
                ('total_cogs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total COGS')),
                ('gross_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Gross Profit')),
                ('notes', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='branches.branch')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='customers.customer')),
                ('pos_terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='pos.posterminal')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='shifts.shift')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'sales_invoices',
                'ordering': ['-invoice_date_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.CharField(choices=[('NEW_COLLECTION', 'New Collection (كريمة / سوبر لوكس)'), ('MIDDLE', 'Middle (وسط / درجة ثانية)'), ('CLEARANCE', 'Clearance (تصفيات / شعبي)'), ('WASTE', 'Waste (تالف / هالك فرز)')], max_length=30)),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Sold Weight (KG)')),
                ('quantity_pieces', models.IntegerField(default=0, verbose_name='Sold Pieces')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Selling Price per Unit/KG')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Line Net Revenue')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit Cost (COGS/KG)')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Line Total COGS')),
                ('gross_profit', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Line Gross Profit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='products.product')),
                ('sale_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.saleinvoice')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='inventory.stockitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'sale_line_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_payments', to='payments.paymentmethod')),
                ('sale_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.saleinvoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'sale_payments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='saleinvoice',
            constraint=models.UniqueConstraint(fields=('tenant', 'invoice_number'), name='unique_sale_invoice_number_per_tenant'),
        ),
    ]
