# Generated by Django 5.1.15 on 2026-09-21 22:37

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0001_initial'),
        ('tenants', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transfer_code', models.CharField(db_index=True, max_length=100, verbose_name='Transfer #')),
                ('transfer_date', models.DateField(verbose_name='Transfer Date')),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft (مسودة)'), ('SHIPPED', 'Shipped / In Transit (تم الشحن / في الطريق)'), ('RECEIVED', 'Received / Completed (تم الاستلام بالمخزن المستهدف)'), ('CANCELLED', 'Cancelled (ملغي)')], db_index=True, default='DRAFT', max_length=20)),
                ('total_weight_kg', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('total_cost_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes', models.TextField(blank=True, null=True)),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='warehouses.warehouse')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_transfers', to=settings.AUTH_USER_MODEL)),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='warehouses.warehouse')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'transfer_orders',
                'ordering': ['-transfer_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.CharField(choices=[('NEW_COLLECTION', 'New Collection (كريمة / سوبر لوكس)'), ('MIDDLE', 'Middle (وسط / درجة ثانية)'), ('CLEARANCE', 'Clearance (تصفيات / شعبي)'), ('WASTE', 'Waste (تالف / هالك فرز)')], max_length=30)),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantity_pieces', models.IntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_lines', to='inventory.stockitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('transfer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transfers.transferorder')),
            ],
            options={
                'db_table': 'transfer_line_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='transferorder',
            constraint=models.UniqueConstraint(fields=('tenant', 'transfer_code'), name='unique_transfer_code_per_tenant'),
        ),
    ]
