# Generated by Django 5.1.15 on 2026-09-25 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('pricing', '0002_add_price_history_model'),
        ('products', '0002_add_legacy_pricing_and_uom_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pricelistitem',
            name='unique_product_grade_per_pricelist',
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_history', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_lists', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_list_items', to='products.product'),
        ),
    ]
