# Generated by Django 5.1.15 on 2026-09-26 07:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_support_branch_and_general_weight_pricing'),
        ('tenants', '0003_add_logo_base64_to_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.CharField(max_length=10)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('kind', models.CharField(blank=True, max_length=10, null=True)),
                ('key', models.CharField(blank=True, max_length=150, null=True)),
                ('segment', models.CharField(blank=True, max_length=100, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('season', models.CharField(blank=True, max_length=100, null=True)),
                ('field', models.CharField(max_length=20)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_changes_v2', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'pricing_change_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PieceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('source_kind', models.CharField(choices=[('BALE', 'Bale (بالة)'), ('STOCK', 'Stock (استوك)'), ('DIRECT', 'Direct / Special (أصناف خاصة)')], max_length=10)),
                ('segment', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('season', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('price_per_piece', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'pricing_piece_items',
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'code'), name='unique_piece_code_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='WeightPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('BALE', 'Bale (بالة)'), ('STOCK', 'Stock (استوك)'), ('DIRECT', 'Direct / Special (أصناف خاصة)')], db_index=True, max_length=10)),
                ('key', models.CharField(blank=True, default='', max_length=150)),
                ('grade', models.CharField(choices=[('NEW_COLLECTION', 'High (عالي)'), ('MIDDLE', 'Medium (وسط)'), ('CLEARANCE', 'Low (تصفيات)')], max_length=20)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'pricing_weight_prices',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'kind', 'key', 'grade'), name='unique_weight_price')],
            },
        ),
    ]
