# Generated by Django 5.1.15 on 2026-09-26 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_offer_pieces_coupons'),
        ('pricing', '0004_pricing_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieceitem',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_pieces', to='discounts.offer'),
        ),
    ]
