# Generated by Django 5.1.15 on 2026-09-28 21:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('pricing', '0005_offer_pieces_coupons'),
        ('tenants', '0003_add_logo_base64_to_tenant'),
        ('warehouses', '0002_add_store_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_kind', models.CharField(default='بالة', max_length=50, verbose_name='نوع الشراء')),
                ('segment', models.CharField(default='حريمي', max_length=50, verbose_name='القسم/الجنس')),
                ('season', models.CharField(default='صيفي', max_length=50, verbose_name='الموسم')),
                ('purchase_grade', models.CharField(default='سوبر كريم', max_length=50, verbose_name='درجة الشراء')),
                ('sort_grade', models.CharField(default='عالي', max_length=50, verbose_name='درجة الفرز')),
                ('category_name', models.CharField(default='بلوزة', max_length=100, verbose_name='الصنف')),
                ('brand', models.CharField(blank=True, default='بدون براند', max_length=100, verbose_name='البراند/التصنيف')),
                ('quantity_pieces', models.IntegerField(default=0, verbose_name='العدد الفعلي المتاح')),
                ('weight_kg', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='الوزن الفعلي (كجم)')),
                ('total_allocated_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='إجمالي التكلفة')),
                ('sorted_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_items', to='branches.branch')),
                ('coding_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_store_items', to='pricing.pieceitem', verbose_name='كود البيع المربوط')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_items', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'store_items',
            },
        ),
    ]
